export const data = [
    {
    "DESTINATION": "Doraville",
    "DIRECTION": "N",
    "EVENT_TIME": "2/06/2023 7:16:08 PM",
    "LINE": "GOLD",
    "NEXT_ARR": "7:16:58 PM",
    "STATION": "LENOX STATION",
    "TRAIN_ID": "303326",
    "WAITING_SECONDS": "47",
    "WAITING_TIME": "Arriving"
    },
    {
    "DESTINATION": "Doraville",
    "DIRECTION": "N",
    "EVENT_TIME": "2/06/2023 7:16:08 PM",
    "LINE": "GOLD",
    "NEXT_ARR": "7:19:44 PM",
    "STATION": "BROOKHAVEN STATION",
    "TRAIN_ID": "303326",
    "WAITING_SECONDS": "213",
    "WAITING_TIME": "3 min"
    },
    {
    "DESTINATION": "Doraville",
    "DIRECTION": "N",
    "EVENT_TIME": "2/06/2023 7:16:08 PM",
    "LINE": "GOLD",
    "NEXT_ARR": "7:23:20 PM",
    "STATION": "CHAMBLEE STATION",
    "TRAIN_ID": "303326",
    "WAITING_SECONDS": "429",
    "WAITING_TIME": "7 min"
    },
    {
    "DESTINATION": "Doraville",
    "DIRECTION": "N",
    "EVENT_TIME": "2/06/2023 7:16:08 PM",
    "LINE": "GOLD",
    "NEXT_ARR": "7:26:21 PM",
    "STATION": "DORAVILLE STATION",
    "TRAIN_ID": "303326",
    "WAITING_SECONDS": "610",
    "WAITING_TIME": "10 min"
    },
    {
    "DESTINATION": "Airport",
    "DIRECTION": "S",
    "EVENT_TIME": "2/06/2023 7:15:45 PM",
    "LINE": "RED",
    "NEXT_ARR": "7:18:44 PM",
    "STATION": "OAKLAND CITY STATION",
    "TRAIN_ID": "401006",
    "WAITING_SECONDS": "153",
    "WAITING_TIME": "2 min"
    },
    {
    "DESTINATION": "Airport",
    "DIRECTION": "S",
    "EVENT_TIME": "2/06/2023 7:15:45 PM",
    "LINE": "RED",
    "NEXT_ARR": "7:20:57 PM",
    "STATION": "LAKEWOOD STATION",
    "TRAIN_ID": "401006",
    "WAITING_SECONDS": "286",
    "WAITING_TIME": "4 min"
    },
    {
    "DESTINATION": "Airport",
    "DIRECTION": "S",
    "EVENT_TIME": "2/06/2023 7:15:45 PM",
    "LINE": "RED",
    "NEXT_ARR": "7:23:45 PM",
    "STATION": "EAST POINT STATION",
    "TRAIN_ID": "401006",
    "WAITING_SECONDS": "454",
    "WAITING_TIME": "7 min"
    },
    {
    "DESTINATION": "Airport",
    "DIRECTION": "S",
    "EVENT_TIME": "2/06/2023 7:15:45 PM",
    "LINE": "RED",
    "NEXT_ARR": "7:26:33 PM",
    "STATION": "COLLEGE PARK STATION",
    "TRAIN_ID": "401006",
    "WAITING_SECONDS": "622",
    "WAITING_TIME": "10 min"
    },
    {
    "DESTINATION": "Airport",
    "DIRECTION": "S",
    "EVENT_TIME": "2/06/2023 7:15:45 PM",
    "LINE": "RED",
    "NEXT_ARR": "7:28:40 PM",
    "STATION": "AIRPORT STATION",
    "TRAIN_ID": "401006",
    "WAITING_SECONDS": "749",
    "WAITING_TIME": "12 min"
    },
    {
    "DESTINATION": "North Springs",
    "DIRECTION": "N",
    "EVENT_TIME": "2/06/2023 7:15:13 PM",
    "LINE": "RED",
    "NEXT_ARR": "7:19:32 PM",
    "STATION": "BUCKHEAD STATION",
    "TRAIN_ID": "403306",
    "WAITING_SECONDS": "201",
    "WAITING_TIME": "3 min"
    },
    {
    "DESTINATION": "North Springs",
    "DIRECTION": "N",
    "EVENT_TIME": "2/06/2023 7:15:13 PM",
    "LINE": "RED",
    "NEXT_ARR": "7:25:07 PM",
    "STATION": "MEDICAL CENTER STATION",
    "TRAIN_ID": "403306",
    "WAITING_SECONDS": "536",
    "WAITING_TIME": "8 min"
    },
    {
    "DESTINATION": "North Springs",
    "DIRECTION": "N",
    "EVENT_TIME": "2/06/2023 7:15:13 PM",
    "LINE": "RED",
    "NEXT_ARR": "7:27:14 PM",
    "STATION": "DUNWOODY STATION",
    "TRAIN_ID": "403306",
    "WAITING_SECONDS": "663",
    "WAITING_TIME": "11 min"
    },
    {
    "DESTINATION": "North Springs",
    "DIRECTION": "N",
    "EVENT_TIME": "2/06/2023 7:15:13 PM",
    "LINE": "RED",
    "NEXT_ARR": "7:29:08 PM",
    "STATION": "SANDY SPRINGS STATION",
    "TRAIN_ID": "403306",
    "WAITING_SECONDS": "777",
    "WAITING_TIME": "12 min"
    },
    {
    "DESTINATION": "North Springs",
    "DIRECTION": "N",
    "EVENT_TIME": "2/06/2023 7:15:13 PM",
    "LINE": "RED",
    "NEXT_ARR": "7:31:44 PM",
    "STATION": "NORTH SPRINGS STATION",
    "TRAIN_ID": "403306",
    "WAITING_SECONDS": "933",
    "WAITING_TIME": "15 min"
    },
    {
    "DESTINATION": "Airport",
    "DIRECTION": "S",
    "EVENT_TIME": "2/06/2023 7:16:10 PM",
    "LINE": "GOLD",
    "NEXT_ARR": "7:17:40 PM",
    "STATION": "WEST END STATION",
    "TRAIN_ID": "301506",
    "WAITING_SECONDS": "89",
    "WAITING_TIME": "1 min"
    },
    {
    "DESTINATION": "Airport",
    "DIRECTION": "S",
    "EVENT_TIME": "2/06/2023 7:16:10 PM",
    "LINE": "GOLD",
    "NEXT_ARR": "7:20:13 PM",
    "STATION": "OAKLAND CITY STATION",
    "TRAIN_ID": "301506",
    "WAITING_SECONDS": "242",
    "WAITING_TIME": "4 min"
    },
    {
    "DESTINATION": "Airport",
    "DIRECTION": "S",
    "EVENT_TIME": "2/06/2023 7:16:10 PM",
    "LINE": "GOLD",
    "NEXT_ARR": "7:22:26 PM",
    "STATION": "LAKEWOOD STATION",
    "TRAIN_ID": "301506",
    "WAITING_SECONDS": "375",
    "WAITING_TIME": "6 min"
    },
    {
    "DESTINATION": "Airport",
    "DIRECTION": "S",
    "EVENT_TIME": "2/06/2023 7:16:10 PM",
    "LINE": "GOLD",
    "NEXT_ARR": "7:25:14 PM",
    "STATION": "EAST POINT STATION",
    "TRAIN_ID": "301506",
    "WAITING_SECONDS": "543",
    "WAITING_TIME": "9 min"
    },
    {
    "DESTINATION": "Airport",
    "DIRECTION": "S",
    "EVENT_TIME": "2/06/2023 7:16:10 PM",
    "LINE": "GOLD",
    "NEXT_ARR": "7:28:02 PM",
    "STATION": "COLLEGE PARK STATION",
    "TRAIN_ID": "301506",
    "WAITING_SECONDS": "711",
    "WAITING_TIME": "11 min"
    },
    {
    "DESTINATION": "Airport",
    "DIRECTION": "S",
    "EVENT_TIME": "2/06/2023 7:16:10 PM",
    "LINE": "GOLD",
    "NEXT_ARR": "7:30:09 PM",
    "STATION": "AIRPORT STATION",
    "TRAIN_ID": "301506",
    "WAITING_SECONDS": "838",
    "WAITING_TIME": "13 min"
    },
    {
    "DESTINATION": "Doraville",
    "DIRECTION": "N",
    "EVENT_TIME": "2/06/2023 7:15:45 PM",
    "LINE": "GOLD",
    "NEXT_ARR": "7:17:46 PM",
    "STATION": "CIVIC CENTER STATION",
    "TRAIN_ID": "304326",
    "WAITING_SECONDS": "95",
    "WAITING_TIME": "1 min"
    },
    {
    "DESTINATION": "Doraville",
    "DIRECTION": "N",
    "EVENT_TIME": "2/06/2023 7:15:45 PM",
    "LINE": "GOLD",
    "NEXT_ARR": "7:18:52 PM",
    "STATION": "NORTH AVE STATION",
    "TRAIN_ID": "304326",
    "WAITING_SECONDS": "161",
    "WAITING_TIME": "2 min"
    },
    {
    "DESTINATION": "Doraville",
    "DIRECTION": "N",
    "EVENT_TIME": "2/06/2023 7:15:45 PM",
    "LINE": "GOLD",
    "NEXT_ARR": "7:20:39 PM",
    "STATION": "MIDTOWN STATION",
    "TRAIN_ID": "304326",
    "WAITING_SECONDS": "268",
    "WAITING_TIME": "4 min"
    },
    {
    "DESTINATION": "Doraville",
    "DIRECTION": "N",
    "EVENT_TIME": "2/06/2023 7:15:45 PM",
    "LINE": "GOLD",
    "NEXT_ARR": "7:22:19 PM",
    "STATION": "ARTS CENTER STATION",
    "TRAIN_ID": "304326",
    "WAITING_SECONDS": "368",
    "WAITING_TIME": "6 min"
    },
    {
    "DESTINATION": "Doraville",
    "DIRECTION": "N",
    "EVENT_TIME": "2/06/2023 7:15:45 PM",
    "LINE": "GOLD",
    "NEXT_ARR": "7:25:48 PM",
    "STATION": "LINDBERGH STATION",
    "TRAIN_ID": "304326",
    "WAITING_SECONDS": "577",
    "WAITING_TIME": "9 min"
    },
    {
    "DESTINATION": "Doraville",
    "DIRECTION": "N",
    "EVENT_TIME": "2/06/2023 7:15:45 PM",
    "LINE": "GOLD",
    "NEXT_ARR": "7:29:31 PM",
    "STATION": "LENOX STATION",
    "TRAIN_ID": "304326",
    "WAITING_SECONDS": "800",
    "WAITING_TIME": "13 min"
    },
    {
    "DESTINATION": "Doraville",
    "DIRECTION": "N",
    "EVENT_TIME": "2/06/2023 7:15:45 PM",
    "LINE": "GOLD",
    "NEXT_ARR": "7:32:17 PM",
    "STATION": "BROOKHAVEN STATION",
    "TRAIN_ID": "304326",
    "WAITING_SECONDS": "966",
    "WAITING_TIME": "16 min"
    },
    {
    "DESTINATION": "Doraville",
    "DIRECTION": "N",
    "EVENT_TIME": "2/06/2023 7:15:45 PM",
    "LINE": "GOLD",
    "NEXT_ARR": "7:35:53 PM",
    "STATION": "CHAMBLEE STATION",
    "TRAIN_ID": "304326",
    "WAITING_SECONDS": "1182",
    "WAITING_TIME": "19 min"
    },
    {
    "DESTINATION": "Doraville",
    "DIRECTION": "N",
    "EVENT_TIME": "2/06/2023 7:15:45 PM",
    "LINE": "GOLD",
    "NEXT_ARR": "7:38:54 PM",
    "STATION": "DORAVILLE STATION",
    "TRAIN_ID": "304326",
    "WAITING_SECONDS": "1363",
    "WAITING_TIME": "22 min"
    },
    {
    "DESTINATION": "Airport",
    "DIRECTION": "S",
    "EVENT_TIME": "2/06/2023 7:15:26 PM",
    "LINE": "RED",
    "NEXT_ARR": "7:17:31 PM",
    "STATION": "MIDTOWN STATION",
    "TRAIN_ID": "402506",
    "WAITING_SECONDS": "80",
    "WAITING_TIME": "1 min"
    },
    {
    "DESTINATION": "Airport",
    "DIRECTION": "S",
    "EVENT_TIME": "2/06/2023 7:15:26 PM",
    "LINE": "RED",
    "NEXT_ARR": "7:19:08 PM",
    "STATION": "NORTH AVE STATION",
    "TRAIN_ID": "402506",
    "WAITING_SECONDS": "177",
    "WAITING_TIME": "2 min"
    },
    {
    "DESTINATION": "Airport",
    "DIRECTION": "S",
    "EVENT_TIME": "2/06/2023 7:15:26 PM",
    "LINE": "RED",
    "NEXT_ARR": "7:20:41 PM",
    "STATION": "CIVIC CENTER STATION",
    "TRAIN_ID": "402506",
    "WAITING_SECONDS": "270",
    "WAITING_TIME": "4 min"
    },
    {
    "DESTINATION": "Airport",
    "DIRECTION": "S",
    "EVENT_TIME": "2/06/2023 7:15:26 PM",
    "LINE": "RED",
    "NEXT_ARR": "7:22:04 PM",
    "STATION": "PEACHTREE CENTER STATION",
    "TRAIN_ID": "402506",
    "WAITING_SECONDS": "353",
    "WAITING_TIME": "5 min"
    },
    {
    "DESTINATION": "Airport",
    "DIRECTION": "S",
    "EVENT_TIME": "2/06/2023 7:15:26 PM",
    "LINE": "RED",
    "NEXT_ARR": "7:24:06 PM",
    "STATION": "FIVE POINTS STATION",
    "TRAIN_ID": "402506",
    "WAITING_SECONDS": "475",
    "WAITING_TIME": "7 min"
    },
    {
    "DESTINATION": "Airport",
    "DIRECTION": "S",
    "EVENT_TIME": "2/06/2023 7:15:26 PM",
    "LINE": "RED",
    "NEXT_ARR": "7:25:49 PM",
    "STATION": "GARNETT STATION",
    "TRAIN_ID": "402506",
    "WAITING_SECONDS": "578",
    "WAITING_TIME": "9 min"
    },
    {
    "DESTINATION": "Airport",
    "DIRECTION": "S",
    "EVENT_TIME": "2/06/2023 7:15:26 PM",
    "LINE": "RED",
    "NEXT_ARR": "7:28:32 PM",
    "STATION": "WEST END STATION",
    "TRAIN_ID": "402506",
    "WAITING_SECONDS": "741",
    "WAITING_TIME": "12 min"
    },
    {
    "DESTINATION": "Airport",
    "DIRECTION": "S",
    "EVENT_TIME": "2/06/2023 7:15:26 PM",
    "LINE": "RED",
    "NEXT_ARR": "7:31:05 PM",
    "STATION": "OAKLAND CITY STATION",
    "TRAIN_ID": "402506",
    "WAITING_SECONDS": "894",
    "WAITING_TIME": "14 min"
    },
    {
    "DESTINATION": "Airport",
    "DIRECTION": "S",
    "EVENT_TIME": "2/06/2023 7:15:26 PM",
    "LINE": "RED",
    "NEXT_ARR": "7:33:18 PM",
    "STATION": "LAKEWOOD STATION",
    "TRAIN_ID": "402506",
    "WAITING_SECONDS": "1027",
    "WAITING_TIME": "17 min"
    },
    {
    "DESTINATION": "Airport",
    "DIRECTION": "S",
    "EVENT_TIME": "2/06/2023 7:15:26 PM",
    "LINE": "RED",
    "NEXT_ARR": "7:36:06 PM",
    "STATION": "EAST POINT STATION",
    "TRAIN_ID": "402506",
    "WAITING_SECONDS": "1195",
    "WAITING_TIME": "19 min"
    },
    {
    "DESTINATION": "Airport",
    "DIRECTION": "S",
    "EVENT_TIME": "2/06/2023 7:15:26 PM",
    "LINE": "RED",
    "NEXT_ARR": "7:38:54 PM",
    "STATION": "COLLEGE PARK STATION",
    "TRAIN_ID": "402506",
    "WAITING_SECONDS": "1363",
    "WAITING_TIME": "22 min"
    },
    {
    "DESTINATION": "Airport",
    "DIRECTION": "S",
    "EVENT_TIME": "2/06/2023 7:15:26 PM",
    "LINE": "RED",
    "NEXT_ARR": "7:41:01 PM",
    "STATION": "AIRPORT STATION",
    "TRAIN_ID": "402506",
    "WAITING_SECONDS": "1490",
    "WAITING_TIME": "24 min"
    },
    {
    "DESTINATION": "Hamilton E Holmes",
    "DIRECTION": "W",
    "EVENT_TIME": "2/06/2023 7:16:11 PM",
    "LINE": "BLUE",
    "NEXT_ARR": "7:16:19 PM",
    "STATION": "INMAN PARK STATION",
    "TRAIN_ID": "106206",
    "WAITING_SECONDS": "8",
    "WAITING_TIME": "Arriving"
    },
    {
    "DESTINATION": "Hamilton E Holmes",
    "DIRECTION": "W",
    "EVENT_TIME": "2/06/2023 7:16:11 PM",
    "LINE": "BLUE",
    "NEXT_ARR": "7:18:48 PM",
    "STATION": "KING MEMORIAL STATION",
    "TRAIN_ID": "106206",
    "WAITING_SECONDS": "157",
    "WAITING_TIME": "2 min"
    },
    {
    "DESTINATION": "Hamilton E Holmes",
    "DIRECTION": "W",
    "EVENT_TIME": "2/06/2023 7:16:11 PM",
    "LINE": "BLUE",
    "NEXT_ARR": "7:20:38 PM",
    "STATION": "GEORGIA STATE STATION",
    "TRAIN_ID": "106206",
    "WAITING_SECONDS": "267",
    "WAITING_TIME": "4 min"
    },
    {
    "DESTINATION": "Hamilton E Holmes",
    "DIRECTION": "W",
    "EVENT_TIME": "2/06/2023 7:16:11 PM",
    "LINE": "BLUE",
    "NEXT_ARR": "7:21:58 PM",
    "STATION": "FIVE POINTS STATION",
    "TRAIN_ID": "106206",
    "WAITING_SECONDS": "347",
    "WAITING_TIME": "5 min"
    },
    {
    "DESTINATION": "Hamilton E Holmes",
    "DIRECTION": "W",
    "EVENT_TIME": "2/06/2023 7:16:11 PM",
    "LINE": "BLUE",
    "NEXT_ARR": "7:23:38 PM",
    "STATION": "OMNI DOME STATION",
    "TRAIN_ID": "106206",
    "WAITING_SECONDS": "447",
    "WAITING_TIME": "7 min"
    },
    {
    "DESTINATION": "Hamilton E Holmes",
    "DIRECTION": "W",
    "EVENT_TIME": "2/06/2023 7:16:11 PM",
    "LINE": "BLUE",
    "NEXT_ARR": "7:24:49 PM",
    "STATION": "VINE CITY STATION",
    "TRAIN_ID": "106206",
    "WAITING_SECONDS": "518",
    "WAITING_TIME": "8 min"
    },
    {
    "DESTINATION": "Hamilton E Holmes",
    "DIRECTION": "W",
    "EVENT_TIME": "2/06/2023 7:16:11 PM",
    "LINE": "BLUE",
    "NEXT_ARR": "7:26:19 PM",
    "STATION": "ASHBY STATION",
    "TRAIN_ID": "106206",
    "WAITING_SECONDS": "608",
    "WAITING_TIME": "10 min"
    },
    {
    "DESTINATION": "Hamilton E Holmes",
    "DIRECTION": "W",
    "EVENT_TIME": "2/06/2023 7:16:11 PM",
    "LINE": "BLUE",
    "NEXT_ARR": "7:28:27 PM",
    "STATION": "WEST LAKE STATION",
    "TRAIN_ID": "106206",
    "WAITING_SECONDS": "736",
    "WAITING_TIME": "12 min"
    },
    {
    "DESTINATION": "Hamilton E Holmes",
    "DIRECTION": "W",
    "EVENT_TIME": "2/06/2023 7:16:11 PM",
    "LINE": "BLUE",
    "NEXT_ARR": "7:31:02 PM",
    "STATION": "HAMILTON E HOLMES STATION",
    "TRAIN_ID": "106206",
    "WAITING_SECONDS": "891",
    "WAITING_TIME": "14 min"
    },
    {
    "DESTINATION": "North Springs",
    "DIRECTION": "N",
    "EVENT_TIME": "2/06/2023 7:16:08 PM",
    "LINE": "RED",
    "NEXT_ARR": "7:16:14 PM",
    "STATION": "FIVE POINTS STATION",
    "TRAIN_ID": "404306",
    "WAITING_SECONDS": "3",
    "WAITING_TIME": "Arriving"
    },
    {
    "DESTINATION": "North Springs",
    "DIRECTION": "N",
    "EVENT_TIME": "2/06/2023 7:16:08 PM",
    "LINE": "RED",
    "NEXT_ARR": "7:18:12 PM",
    "STATION": "PEACHTREE CENTER STATION",
    "TRAIN_ID": "404306",
    "WAITING_SECONDS": "121",
    "WAITING_TIME": "2 min"
    },
    {
    "DESTINATION": "North Springs",
    "DIRECTION": "N",
    "EVENT_TIME": "2/06/2023 7:16:08 PM",
    "LINE": "RED",
    "NEXT_ARR": "7:19:47 PM",
    "STATION": "CIVIC CENTER STATION",
    "TRAIN_ID": "404306",
    "WAITING_SECONDS": "216",
    "WAITING_TIME": "3 min"
    },
    {
    "DESTINATION": "North Springs",
    "DIRECTION": "N",
    "EVENT_TIME": "2/06/2023 7:16:08 PM",
    "LINE": "RED",
    "NEXT_ARR": "7:20:53 PM",
    "STATION": "NORTH AVE STATION",
    "TRAIN_ID": "404306",
    "WAITING_SECONDS": "282",
    "WAITING_TIME": "4 min"
    },
    {
    "DESTINATION": "North Springs",
    "DIRECTION": "N",
    "EVENT_TIME": "2/06/2023 7:16:08 PM",
    "LINE": "RED",
    "NEXT_ARR": "7:22:40 PM",
    "STATION": "MIDTOWN STATION",
    "TRAIN_ID": "404306",
    "WAITING_SECONDS": "389",
    "WAITING_TIME": "6 min"
    },
    {
    "DESTINATION": "North Springs",
    "DIRECTION": "N",
    "EVENT_TIME": "2/06/2023 7:16:08 PM",
    "LINE": "RED",
    "NEXT_ARR": "7:24:20 PM",
    "STATION": "ARTS CENTER STATION",
    "TRAIN_ID": "404306",
    "WAITING_SECONDS": "489",
    "WAITING_TIME": "8 min"
    },
    {
    "DESTINATION": "North Springs",
    "DIRECTION": "N",
    "EVENT_TIME": "2/06/2023 7:16:08 PM",
    "LINE": "RED",
    "NEXT_ARR": "7:27:49 PM",
    "STATION": "LINDBERGH STATION",
    "TRAIN_ID": "404306",
    "WAITING_SECONDS": "698",
    "WAITING_TIME": "11 min"
    },
    {
    "DESTINATION": "North Springs",
    "DIRECTION": "N",
    "EVENT_TIME": "2/06/2023 7:16:08 PM",
    "LINE": "RED",
    "NEXT_ARR": "7:31:10 PM",
    "STATION": "BUCKHEAD STATION",
    "TRAIN_ID": "404306",
    "WAITING_SECONDS": "899",
    "WAITING_TIME": "14 min"
    },
    {
    "DESTINATION": "North Springs",
    "DIRECTION": "N",
    "EVENT_TIME": "2/06/2023 7:16:08 PM",
    "LINE": "RED",
    "NEXT_ARR": "7:36:45 PM",
    "STATION": "MEDICAL CENTER STATION",
    "TRAIN_ID": "404306",
    "WAITING_SECONDS": "1234",
    "WAITING_TIME": "20 min"
    },
    {
    "DESTINATION": "North Springs",
    "DIRECTION": "N",
    "EVENT_TIME": "2/06/2023 7:16:08 PM",
    "LINE": "RED",
    "NEXT_ARR": "7:38:52 PM",
    "STATION": "DUNWOODY STATION",
    "TRAIN_ID": "404306",
    "WAITING_SECONDS": "1361",
    "WAITING_TIME": "22 min"
    },
    {
    "DESTINATION": "North Springs",
    "DIRECTION": "N",
    "EVENT_TIME": "2/06/2023 7:16:08 PM",
    "LINE": "RED",
    "NEXT_ARR": "7:40:46 PM",
    "STATION": "SANDY SPRINGS STATION",
    "TRAIN_ID": "404306",
    "WAITING_SECONDS": "1475",
    "WAITING_TIME": "24 min"
    },
    {
    "DESTINATION": "North Springs",
    "DIRECTION": "N",
    "EVENT_TIME": "2/06/2023 7:16:08 PM",
    "LINE": "RED",
    "NEXT_ARR": "7:43:22 PM",
    "STATION": "NORTH SPRINGS STATION",
    "TRAIN_ID": "404306",
    "WAITING_SECONDS": "1631",
    "WAITING_TIME": "27 min"
    },
    {
    "DESTINATION": "Indian Creek",
    "DIRECTION": "E",
    "EVENT_TIME": "2/06/2023 7:16:08 PM",
    "LINE": "BLUE",
    "NEXT_ARR": "7:17:48 PM",
    "STATION": "INMAN PARK STATION",
    "TRAIN_ID": "103006",
    "WAITING_SECONDS": "97",
    "WAITING_TIME": "1 min"
    },
    {
    "DESTINATION": "Indian Creek",
    "DIRECTION": "E",
    "EVENT_TIME": "2/06/2023 7:16:08 PM",
    "LINE": "BLUE",
    "NEXT_ARR": "7:19:43 PM",
    "STATION": "EDGEWOOD CANDLER PARK STATION",
    "TRAIN_ID": "103006",
    "WAITING_SECONDS": "212",
    "WAITING_TIME": "3 min"
    },
    {
    "DESTINATION": "Indian Creek",
    "DIRECTION": "E",
    "EVENT_TIME": "2/06/2023 7:16:08 PM",
    "LINE": "BLUE",
    "NEXT_ARR": "7:22:35 PM",
    "STATION": "EAST LAKE STATION",
    "TRAIN_ID": "103006",
    "WAITING_SECONDS": "384",
    "WAITING_TIME": "6 min"
    },
    {
    "DESTINATION": "Indian Creek",
    "DIRECTION": "E",
    "EVENT_TIME": "2/06/2023 7:16:08 PM",
    "LINE": "BLUE",
    "NEXT_ARR": "7:25:59 PM",
    "STATION": "DECATUR STATION",
    "TRAIN_ID": "103006",
    "WAITING_SECONDS": "588",
    "WAITING_TIME": "9 min"
    },
    {
    "DESTINATION": "Indian Creek",
    "DIRECTION": "E",
    "EVENT_TIME": "2/06/2023 7:16:08 PM",
    "LINE": "BLUE",
    "NEXT_ARR": "7:28:18 PM",
    "STATION": "AVONDALE STATION",
    "TRAIN_ID": "103006",
    "WAITING_SECONDS": "727",
    "WAITING_TIME": "12 min"
    },
    {
    "DESTINATION": "Indian Creek",
    "DIRECTION": "E",
    "EVENT_TIME": "2/06/2023 7:16:08 PM",
    "LINE": "BLUE",
    "NEXT_ARR": "7:31:16 PM",
    "STATION": "KENSINGTON STATION",
    "TRAIN_ID": "103006",
    "WAITING_SECONDS": "905",
    "WAITING_TIME": "15 min"
    },
    {
    "DESTINATION": "Indian Creek",
    "DIRECTION": "E",
    "EVENT_TIME": "2/06/2023 7:16:08 PM",
    "LINE": "BLUE",
    "NEXT_ARR": "7:33:49 PM",
    "STATION": "INDIAN CREEK STATION",
    "TRAIN_ID": "103006",
    "WAITING_SECONDS": "1058",
    "WAITING_TIME": "17 min"
    },
    {
    "DESTINATION": "Airport",
    "DIRECTION": "S",
    "EVENT_TIME": "2/06/2023 7:16:10 PM",
    "LINE": "GOLD",
    "NEXT_ARR": "7:19:54 PM",
    "STATION": "ARTS CENTER STATION",
    "TRAIN_ID": "302006",
    "WAITING_SECONDS": "223",
    "WAITING_TIME": "3 min"
    },
    {
    "DESTINATION": "Airport",
    "DIRECTION": "S",
    "EVENT_TIME": "2/06/2023 7:16:10 PM",
    "LINE": "GOLD",
    "NEXT_ARR": "7:21:26 PM",
    "STATION": "MIDTOWN STATION",
    "TRAIN_ID": "302006",
    "WAITING_SECONDS": "315",
    "WAITING_TIME": "5 min"
    },
    {
    "DESTINATION": "Airport",
    "DIRECTION": "S",
    "EVENT_TIME": "2/06/2023 7:16:10 PM",
    "LINE": "GOLD",
    "NEXT_ARR": "7:23:03 PM",
    "STATION": "NORTH AVE STATION",
    "TRAIN_ID": "302006",
    "WAITING_SECONDS": "412",
    "WAITING_TIME": "6 min"
    },
    {
    "DESTINATION": "Airport",
    "DIRECTION": "S",
    "EVENT_TIME": "2/06/2023 7:16:10 PM",
    "LINE": "GOLD",
    "NEXT_ARR": "7:24:36 PM",
    "STATION": "CIVIC CENTER STATION",
    "TRAIN_ID": "302006",
    "WAITING_SECONDS": "505",
    "WAITING_TIME": "8 min"
    },
    {
    "DESTINATION": "Airport",
    "DIRECTION": "S",
    "EVENT_TIME": "2/06/2023 7:16:10 PM",
    "LINE": "GOLD",
    "NEXT_ARR": "7:25:59 PM",
    "STATION": "PEACHTREE CENTER STATION",
    "TRAIN_ID": "302006",
    "WAITING_SECONDS": "588",
    "WAITING_TIME": "9 min"
    },
    {
    "DESTINATION": "Airport",
    "DIRECTION": "S",
    "EVENT_TIME": "2/06/2023 7:16:10 PM",
    "LINE": "GOLD",
    "NEXT_ARR": "7:28:01 PM",
    "STATION": "FIVE POINTS STATION",
    "TRAIN_ID": "302006",
    "WAITING_SECONDS": "710",
    "WAITING_TIME": "11 min"
    },
    {
    "DESTINATION": "Airport",
    "DIRECTION": "S",
    "EVENT_TIME": "2/06/2023 7:16:10 PM",
    "LINE": "GOLD",
    "NEXT_ARR": "7:29:44 PM",
    "STATION": "GARNETT STATION",
    "TRAIN_ID": "302006",
    "WAITING_SECONDS": "813",
    "WAITING_TIME": "13 min"
    },
    {
    "DESTINATION": "Airport",
    "DIRECTION": "S",
    "EVENT_TIME": "2/06/2023 7:16:10 PM",
    "LINE": "GOLD",
    "NEXT_ARR": "7:32:27 PM",
    "STATION": "WEST END STATION",
    "TRAIN_ID": "302006",
    "WAITING_SECONDS": "976",
    "WAITING_TIME": "16 min"
    },
    {
    "DESTINATION": "Airport",
    "DIRECTION": "S",
    "EVENT_TIME": "2/06/2023 7:16:10 PM",
    "LINE": "GOLD",
    "NEXT_ARR": "7:35:00 PM",
    "STATION": "OAKLAND CITY STATION",
    "TRAIN_ID": "302006",
    "WAITING_SECONDS": "1129",
    "WAITING_TIME": "18 min"
    },
    {
    "DESTINATION": "Airport",
    "DIRECTION": "S",
    "EVENT_TIME": "2/06/2023 7:16:10 PM",
    "LINE": "GOLD",
    "NEXT_ARR": "7:37:13 PM",
    "STATION": "LAKEWOOD STATION",
    "TRAIN_ID": "302006",
    "WAITING_SECONDS": "1262",
    "WAITING_TIME": "21 min"
    },
    {
    "DESTINATION": "Airport",
    "DIRECTION": "S",
    "EVENT_TIME": "2/06/2023 7:16:10 PM",
    "LINE": "GOLD",
    "NEXT_ARR": "7:40:01 PM",
    "STATION": "EAST POINT STATION",
    "TRAIN_ID": "302006",
    "WAITING_SECONDS": "1430",
    "WAITING_TIME": "23 min"
    },
    {
    "DESTINATION": "Airport",
    "DIRECTION": "S",
    "EVENT_TIME": "2/06/2023 7:16:10 PM",
    "LINE": "GOLD",
    "NEXT_ARR": "7:42:49 PM",
    "STATION": "COLLEGE PARK STATION",
    "TRAIN_ID": "302006",
    "WAITING_SECONDS": "1598",
    "WAITING_TIME": "26 min"
    },
    {
    "DESTINATION": "Airport",
    "DIRECTION": "S",
    "EVENT_TIME": "2/06/2023 7:16:10 PM",
    "LINE": "GOLD",
    "NEXT_ARR": "7:44:56 PM",
    "STATION": "AIRPORT STATION",
    "TRAIN_ID": "302006",
    "WAITING_SECONDS": "1725",
    "WAITING_TIME": "28 min"
    },
    {
    "DESTINATION": "Doraville",
    "DIRECTION": "N",
    "EVENT_TIME": "2/06/2023 7:16:06 PM",
    "LINE": "GOLD",
    "NEXT_ARR": "7:16:21 PM",
    "STATION": "LAKEWOOD STATION",
    "TRAIN_ID": "305326",
    "WAITING_SECONDS": "10",
    "WAITING_TIME": "Arriving"
    },
    {
    "DESTINATION": "Doraville",
    "DIRECTION": "N",
    "EVENT_TIME": "2/06/2023 7:16:06 PM",
    "LINE": "GOLD",
    "NEXT_ARR": "7:18:24 PM",
    "STATION": "OAKLAND CITY STATION",
    "TRAIN_ID": "305326",
    "WAITING_SECONDS": "133",
    "WAITING_TIME": "2 min"
    },
    {
    "DESTINATION": "Doraville",
    "DIRECTION": "N",
    "EVENT_TIME": "2/06/2023 7:16:06 PM",
    "LINE": "GOLD",
    "NEXT_ARR": "7:21:09 PM",
    "STATION": "WEST END STATION",
    "TRAIN_ID": "305326",
    "WAITING_SECONDS": "298",
    "WAITING_TIME": "4 min"
    },
    {
    "DESTINATION": "Doraville",
    "DIRECTION": "N",
    "EVENT_TIME": "2/06/2023 7:16:06 PM",
    "LINE": "GOLD",
    "NEXT_ARR": "7:23:56 PM",
    "STATION": "GARNETT STATION",
    "TRAIN_ID": "305326",
    "WAITING_SECONDS": "465",
    "WAITING_TIME": "7 min"
    },
    {
    "DESTINATION": "Doraville",
    "DIRECTION": "N",
    "EVENT_TIME": "2/06/2023 7:16:06 PM",
    "LINE": "GOLD",
    "NEXT_ARR": "7:25:20 PM",
    "STATION": "FIVE POINTS STATION",
    "TRAIN_ID": "305326",
    "WAITING_SECONDS": "549",
    "WAITING_TIME": "9 min"
    },
    {
    "DESTINATION": "Doraville",
    "DIRECTION": "N",
    "EVENT_TIME": "2/06/2023 7:16:06 PM",
    "LINE": "GOLD",
    "NEXT_ARR": "7:27:18 PM",
    "STATION": "PEACHTREE CENTER STATION",
    "TRAIN_ID": "305326",
    "WAITING_SECONDS": "667",
    "WAITING_TIME": "11 min"
    },
    {
    "DESTINATION": "Doraville",
    "DIRECTION": "N",
    "EVENT_TIME": "2/06/2023 7:16:06 PM",
    "LINE": "GOLD",
    "NEXT_ARR": "7:28:53 PM",
    "STATION": "CIVIC CENTER STATION",
    "TRAIN_ID": "305326",
    "WAITING_SECONDS": "762",
    "WAITING_TIME": "12 min"
    },
    {
    "DESTINATION": "Doraville",
    "DIRECTION": "N",
    "EVENT_TIME": "2/06/2023 7:16:06 PM",
    "LINE": "GOLD",
    "NEXT_ARR": "7:29:59 PM",
    "STATION": "NORTH AVE STATION",
    "TRAIN_ID": "305326",
    "WAITING_SECONDS": "828",
    "WAITING_TIME": "13 min"
    },
    {
    "DESTINATION": "Doraville",
    "DIRECTION": "N",
    "EVENT_TIME": "2/06/2023 7:16:06 PM",
    "LINE": "GOLD",
    "NEXT_ARR": "7:31:46 PM",
    "STATION": "MIDTOWN STATION",
    "TRAIN_ID": "305326",
    "WAITING_SECONDS": "935",
    "WAITING_TIME": "15 min"
    },
    {
    "DESTINATION": "Doraville",
    "DIRECTION": "N",
    "EVENT_TIME": "2/06/2023 7:16:06 PM",
    "LINE": "GOLD",
    "NEXT_ARR": "7:33:26 PM",
    "STATION": "ARTS CENTER STATION",
    "TRAIN_ID": "305326",
    "WAITING_SECONDS": "1035",
    "WAITING_TIME": "17 min"
    },
    {
    "DESTINATION": "Doraville",
    "DIRECTION": "N",
    "EVENT_TIME": "2/06/2023 7:16:06 PM",
    "LINE": "GOLD",
    "NEXT_ARR": "7:36:55 PM",
    "STATION": "LINDBERGH STATION",
    "TRAIN_ID": "305326",
    "WAITING_SECONDS": "1244",
    "WAITING_TIME": "20 min"
    },
    {
    "DESTINATION": "Doraville",
    "DIRECTION": "N",
    "EVENT_TIME": "2/06/2023 7:16:06 PM",
    "LINE": "GOLD",
    "NEXT_ARR": "7:40:38 PM",
    "STATION": "LENOX STATION",
    "TRAIN_ID": "305326",
    "WAITING_SECONDS": "1467",
    "WAITING_TIME": "24 min"
    },
    {
    "DESTINATION": "Doraville",
    "DIRECTION": "N",
    "EVENT_TIME": "2/06/2023 7:16:06 PM",
    "LINE": "GOLD",
    "NEXT_ARR": "7:43:24 PM",
    "STATION": "BROOKHAVEN STATION",
    "TRAIN_ID": "305326",
    "WAITING_SECONDS": "1633",
    "WAITING_TIME": "27 min"
    },
    {
    "DESTINATION": "Doraville",
    "DIRECTION": "N",
    "EVENT_TIME": "2/06/2023 7:16:06 PM",
    "LINE": "GOLD",
    "NEXT_ARR": "7:47:00 PM",
    "STATION": "CHAMBLEE STATION",
    "TRAIN_ID": "305326",
    "WAITING_SECONDS": "1849",
    "WAITING_TIME": "30 min"
    },
    {
    "DESTINATION": "Doraville",
    "DIRECTION": "N",
    "EVENT_TIME": "2/06/2023 7:16:06 PM",
    "LINE": "GOLD",
    "NEXT_ARR": "7:50:01 PM",
    "STATION": "DORAVILLE STATION",
    "TRAIN_ID": "305326",
    "WAITING_SECONDS": "2030",
    "WAITING_TIME": "33 min"
    },
    {
    "DESTINATION": "Bankhead",
    "DIRECTION": "W",
    "EVENT_TIME": "2/06/2023 7:15:33 PM",
    "LINE": "GREEN",
    "NEXT_ARR": "7:17:22 PM",
    "STATION": "VINE CITY STATION",
    "TRAIN_ID": "203252",
    "WAITING_SECONDS": "71",
    "WAITING_TIME": "1 min"
    },
    {
    "DESTINATION": "Bankhead",
    "DIRECTION": "W",
    "EVENT_TIME": "2/06/2023 7:15:33 PM",
    "LINE": "GREEN",
    "NEXT_ARR": "7:18:52 PM",
    "STATION": "ASHBY STATION",
    "TRAIN_ID": "203252",
    "WAITING_SECONDS": "161",
    "WAITING_TIME": "2 min"
    },
    {
    "DESTINATION": "Bankhead",
    "DIRECTION": "W",
    "EVENT_TIME": "2/06/2023 7:15:33 PM",
    "LINE": "GREEN",
    "NEXT_ARR": "7:21:09 PM",
    "STATION": "BANKHEAD STATION",
    "TRAIN_ID": "203252",
    "WAITING_SECONDS": "298",
    "WAITING_TIME": "4 min"
    },
    {
    "DESTINATION": "Airport",
    "DIRECTION": "S",
    "EVENT_TIME": "2/06/2023 7:15:35 PM",
    "LINE": "RED",
    "NEXT_ARR": "7:22:00 PM",
    "STATION": "BUCKHEAD STATION",
    "TRAIN_ID": "405506",
    "WAITING_SECONDS": "349",
    "WAITING_TIME": "5 min"
    },
    {
    "DESTINATION": "Airport",
    "DIRECTION": "S",
    "EVENT_TIME": "2/06/2023 7:15:35 PM",
    "LINE": "RED",
    "NEXT_ARR": "7:25:44 PM",
    "STATION": "LINDBERGH STATION",
    "TRAIN_ID": "405506",
    "WAITING_SECONDS": "573",
    "WAITING_TIME": "9 min"
    },
    {
    "DESTINATION": "Airport",
    "DIRECTION": "S",
    "EVENT_TIME": "2/06/2023 7:15:35 PM",
    "LINE": "RED",
    "NEXT_ARR": "7:29:27 PM",
    "STATION": "ARTS CENTER STATION",
    "TRAIN_ID": "405506",
    "WAITING_SECONDS": "796",
    "WAITING_TIME": "13 min"
    },
    {
    "DESTINATION": "Airport",
    "DIRECTION": "S",
    "EVENT_TIME": "2/06/2023 7:15:35 PM",
    "LINE": "RED",
    "NEXT_ARR": "7:30:59 PM",
    "STATION": "MIDTOWN STATION",
    "TRAIN_ID": "405506",
    "WAITING_SECONDS": "888",
    "WAITING_TIME": "14 min"
    },
    {
    "DESTINATION": "Airport",
    "DIRECTION": "S",
    "EVENT_TIME": "2/06/2023 7:15:35 PM",
    "LINE": "RED",
    "NEXT_ARR": "7:32:36 PM",
    "STATION": "NORTH AVE STATION",
    "TRAIN_ID": "405506",
    "WAITING_SECONDS": "985",
    "WAITING_TIME": "16 min"
    },
    {
    "DESTINATION": "Airport",
    "DIRECTION": "S",
    "EVENT_TIME": "2/06/2023 7:15:35 PM",
    "LINE": "RED",
    "NEXT_ARR": "7:34:09 PM",
    "STATION": "CIVIC CENTER STATION",
    "TRAIN_ID": "405506",
    "WAITING_SECONDS": "1078",
    "WAITING_TIME": "17 min"
    },
    {
    "DESTINATION": "Airport",
    "DIRECTION": "S",
    "EVENT_TIME": "2/06/2023 7:15:35 PM",
    "LINE": "RED",
    "NEXT_ARR": "7:35:32 PM",
    "STATION": "PEACHTREE CENTER STATION",
    "TRAIN_ID": "405506",
    "WAITING_SECONDS": "1161",
    "WAITING_TIME": "19 min"
    },
    {
    "DESTINATION": "Airport",
    "DIRECTION": "S",
    "EVENT_TIME": "2/06/2023 7:15:35 PM",
    "LINE": "RED",
    "NEXT_ARR": "7:37:34 PM",
    "STATION": "FIVE POINTS STATION",
    "TRAIN_ID": "405506",
    "WAITING_SECONDS": "1283",
    "WAITING_TIME": "21 min"
    },
    {
    "DESTINATION": "Airport",
    "DIRECTION": "S",
    "EVENT_TIME": "2/06/2023 7:15:35 PM",
    "LINE": "RED",
    "NEXT_ARR": "7:39:17 PM",
    "STATION": "GARNETT STATION",
    "TRAIN_ID": "405506",
    "WAITING_SECONDS": "1386",
    "WAITING_TIME": "23 min"
    },
    {
    "DESTINATION": "Airport",
    "DIRECTION": "S",
    "EVENT_TIME": "2/06/2023 7:15:35 PM",
    "LINE": "RED",
    "NEXT_ARR": "7:42:00 PM",
    "STATION": "WEST END STATION",
    "TRAIN_ID": "405506",
    "WAITING_SECONDS": "1549",
    "WAITING_TIME": "25 min"
    },
    {
    "DESTINATION": "Airport",
    "DIRECTION": "S",
    "EVENT_TIME": "2/06/2023 7:15:35 PM",
    "LINE": "RED",
    "NEXT_ARR": "7:44:33 PM",
    "STATION": "OAKLAND CITY STATION",
    "TRAIN_ID": "405506",
    "WAITING_SECONDS": "1702",
    "WAITING_TIME": "28 min"
    },
    {
    "DESTINATION": "Airport",
    "DIRECTION": "S",
    "EVENT_TIME": "2/06/2023 7:15:35 PM",
    "LINE": "RED",
    "NEXT_ARR": "7:46:46 PM",
    "STATION": "LAKEWOOD STATION",
    "TRAIN_ID": "405506",
    "WAITING_SECONDS": "1835",
    "WAITING_TIME": "30 min"
    },
    {
    "DESTINATION": "Airport",
    "DIRECTION": "S",
    "EVENT_TIME": "2/06/2023 7:15:35 PM",
    "LINE": "RED",
    "NEXT_ARR": "7:49:34 PM",
    "STATION": "EAST POINT STATION",
    "TRAIN_ID": "405506",
    "WAITING_SECONDS": "2003",
    "WAITING_TIME": "33 min"
    },
    {
    "DESTINATION": "Airport",
    "DIRECTION": "S",
    "EVENT_TIME": "2/06/2023 7:15:35 PM",
    "LINE": "RED",
    "NEXT_ARR": "7:52:22 PM",
    "STATION": "COLLEGE PARK STATION",
    "TRAIN_ID": "405506",
    "WAITING_SECONDS": "2171",
    "WAITING_TIME": "36 min"
    },
    {
    "DESTINATION": "Airport",
    "DIRECTION": "S",
    "EVENT_TIME": "2/06/2023 7:15:35 PM",
    "LINE": "RED",
    "NEXT_ARR": "7:54:29 PM",
    "STATION": "AIRPORT STATION",
    "TRAIN_ID": "405506",
    "WAITING_SECONDS": "2298",
    "WAITING_TIME": "38 min"
    },
    {
    "DESTINATION": "Edgewood Candler Park",
    "DIRECTION": "E",
    "EVENT_TIME": "2/06/2023 7:16:07 PM",
    "LINE": "GREEN",
    "NEXT_ARR": "7:17:46 PM",
    "STATION": "VINE CITY STATION",
    "TRAIN_ID": "204096",
    "WAITING_SECONDS": "95",
    "WAITING_TIME": "1 min"
    },
    {
    "DESTINATION": "Edgewood Candler Park",
    "DIRECTION": "E",
    "EVENT_TIME": "2/06/2023 7:16:07 PM",
    "LINE": "GREEN",
    "NEXT_ARR": "7:18:55 PM",
    "STATION": "OMNI DOME STATION",
    "TRAIN_ID": "204096",
    "WAITING_SECONDS": "164",
    "WAITING_TIME": "2 min"
    },
    {
    "DESTINATION": "Edgewood Candler Park",
    "DIRECTION": "E",
    "EVENT_TIME": "2/06/2023 7:16:07 PM",
    "LINE": "GREEN",
    "NEXT_ARR": "7:20:08 PM",
    "STATION": "FIVE POINTS STATION",
    "TRAIN_ID": "204096",
    "WAITING_SECONDS": "237",
    "WAITING_TIME": "3 min"
    },
    {
    "DESTINATION": "Edgewood Candler Park",
    "DIRECTION": "E",
    "EVENT_TIME": "2/06/2023 7:16:07 PM",
    "LINE": "GREEN",
    "NEXT_ARR": "7:21:29 PM",
    "STATION": "GEORGIA STATE STATION",
    "TRAIN_ID": "204096",
    "WAITING_SECONDS": "318",
    "WAITING_TIME": "5 min"
    },
    {
    "DESTINATION": "Edgewood Candler Park",
    "DIRECTION": "E",
    "EVENT_TIME": "2/06/2023 7:16:07 PM",
    "LINE": "GREEN",
    "NEXT_ARR": "7:23:16 PM",
    "STATION": "KING MEMORIAL STATION",
    "TRAIN_ID": "204096",
    "WAITING_SECONDS": "425",
    "WAITING_TIME": "7 min"
    },
    {
    "DESTINATION": "Edgewood Candler Park",
    "DIRECTION": "E",
    "EVENT_TIME": "2/06/2023 7:16:07 PM",
    "LINE": "GREEN",
    "NEXT_ARR": "7:25:47 PM",
    "STATION": "INMAN PARK STATION",
    "TRAIN_ID": "204096",
    "WAITING_SECONDS": "576",
    "WAITING_TIME": "9 min"
    },
    {
    "DESTINATION": "Edgewood Candler Park",
    "DIRECTION": "E",
    "EVENT_TIME": "2/06/2023 7:16:07 PM",
    "LINE": "GREEN",
    "NEXT_ARR": "7:27:42 PM",
    "STATION": "EDGEWOOD CANDLER PARK STATION",
    "TRAIN_ID": "204096",
    "WAITING_SECONDS": "691",
    "WAITING_TIME": "11 min"
    },
    {
    "DESTINATION": "Airport",
    "DIRECTION": "S",
    "EVENT_TIME": "2/06/2023 7:16:10 PM",
    "LINE": "GOLD",
    "NEXT_ARR": "7:16:11 PM",
    "STATION": "LINDBERGH STATION",
    "TRAIN_ID": "302006",
    "WAITING_SECONDS": "0",
    "WAITING_TIME": "Arriving"
    }
    ]